{
  "name": "graphql-playground-react",
  "version": "1.7.27",
  "main": "./lib/lib.js",
  "typings": "./lib/lib.d.ts",
  "description": "GraphQL IDE for better development workflows (GraphQL Subscriptions, interactive docs & collaboration).",
  "contributors": [
    "Tim Suchanek <tim@graph.cool>",
    "Johannes Schickling <johannes@graph.cool>",
    "Lukas Huvar <lukas@huvar.cz>"
  ],
  "repository": {
    "type": "git",
    "url": "http://github.com/graphcool/graphql-playground.git"
  },
  "license": "MIT",
  "scripts": {
    "start": "node scripts/start.js",
    "start:analyze": "ANALYZE_BUNDLE=true node scripts/start.js",
    "start:graphql-bin": "ACTIVE_APP=graphqlbin node scripts/start.js",
    "prepublishOnly": "yarn build",
    "build": "rimraf dist build dist && yarn build-app && yarn build-package",
    "tsc": "tsc -p tsconfig.build.json",
    "build-package": "rimraf lib build/dist && npm run tsc && babel lib -d lib && cp -r ./src/assets/ ./lib/assets/ && cd lib && rimraf *.jsx;",
    "build-app": "node scripts/build.js",
    "test": "jest",
    "bundlesize": "bundlesize",
    "bump": "npm version patch --no-git-tag-version && git add package.json",
    "graphql-faker": "graphql-faker ./tests/schema.faker.graphql",
    "lint": "tslint \"src/**/*.ts{,x}\"",
    "precommit": "lint-staged",
    "prettier": "prettier --single-quote --no-semi --trailing-comma all --write *.{ts,tsx} 'src/**/*.{ts,tsx}'"
  },
  "files": [
    "build",
    "lib",
    "playground.css"
  ],
  "bundlesize": [
    {
      "path": "build/static/js/index.js",
      "maxSize": "674 kB"
    }
  ],
  "devDependencies": {
    "@babel/cli": "^7.0.0",
    "@babel/core": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/plugin-proposal-json-strings": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-syntax-import-meta": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "@types/deasync": "0.1.0",
    "@types/escape-html": "^1.0.1",
    "@types/jest": "22.2.3",
    "@types/markdown-it": "^12.2.3",
    "@types/node": "12.12.34",
    "@types/react": "16.9.32",
    "@types/zen-observable": "^0.5.3",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^23.4.2",
    "babel-loader": "^8.0.0",
    "babel-plugin-styled-components": "^1.8.0",
    "bundlesize": "^0.17.0",
    "case-sensitive-paths-webpack-plugin": "2.3.0",
    "chalk": "2.4.1",
    "connect-history-api-fallback": "1.5.0",
    "cross-spawn": "6.0.5",
    "css-loader": "3.4.2",
    "detect-port": "1.2.3",
    "dotenv": "5.0.1",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "enzyme-to-json": "^3.3.4",
    "extract-text-webpack-plugin": "4.0.0-beta.0",
    "file-loader": "6.0.0",
    "filesize": "6.1.0",
    "fs-extra": "5.0.0",
    "graphql-playground-html": "1.5.6",
    "gzip-size": "4.1.0",
    "html-webpack-plugin": "4.0.4",
    "http-proxy-middleware": "0.17.4",
    "husky": "0.14.3",
    "jest": "22.1.4",
    "jest-localstorage-mock": "^2.2.0",
    "json-loader": "0.5.7",
    "lint-staged": "6.1.0",
    "node-noop": "1.0.0",
    "object-assign": "4.1.1",
    "promise": "8.0.1",
    "raw-loader": "4.0.0",
    "react-dev-utils": "10.1.0",
    "recursive-readdir": "2.2.2",
    "rimraf": "3.0.2",
    "source-map-loader": "0.2.4",
    "strip-ansi": "4.0.0",
    "style-loader": "1.1.3",
    "svg-inline-loader": "0.8.2",
    "sw-precache-webpack-plugin": "1.0.0",
    "ts-loader": "6.2.2",
    "tslint": "5.10.0",
    "tslint-graphcool-frontend": "0.0.3",
    "tslint-loader": "3.6.0",
    "typescript": "3.8.3",
    "typescript-styled-plugin": "^0.11.0",
    "url-loader": "4.0.0",
    "webpack": "4.44.1",
    "webpack-dev-server": "3.11.0",
    "webpack-manifest-plugin": "2.2.0",
    "why-did-you-update": "0.1.1"
  },
  "dependencies": {
    "@types/lru-cache": "^4.1.1",
    "apollo-link": "^1.2.13",
    "apollo-link-http": "^1.5.16",
    "apollo-link-ws": "^1.0.19",
    "calculate-size": "^1.1.1",
    "codemirror": "^5.58.1",
    "codemirror-graphql": "^0.12.3",
    "copy-to-clipboard": "^3.0.8",
    "cryptiles": "4.1.2",
    "cuid": "^1.3.8",
    "escape-html": "^1.0.3",
    "graphiql": "^0.17.5",
    "graphql": "^15.3.0",
    "immutable": "^4.0.0-rc.9",
    "isomorphic-fetch": "^2.2.1",
    "js-yaml": "^3.10.0",
    "json-stable-stringify": "^1.0.1",
    "keycode": "^2.1.9",
    "lodash": "^4.17.11",
    "lodash.debounce": "^4.0.8",
    "lru-cache": "^6.0.0",
    "markdown-it": "^12.2.0",
    "prettier": "2.0.2",
    "prop-types": "^15.7.2",
    "query-string": "5",
    "react": "16.13.1",
    "react-addons-shallow-compare": "^15.6.2",
    "react-codemirror": "^1.0.0",
    "react-copy-to-clipboard": "^5.0.1",
    "react-display-name": "^0.2.3",
    "react-dom": "^16.13.1",
    "react-helmet": "^5.2.0",
    "react-input-autosize": "^2.2.1",
    "react-modal": "^3.1.11",
    "react-redux": "^7.2.1",
    "react-router-dom": "^4.2.2",
    "react-sortable-hoc": "^0.8.3",
    "react-transition-group": "^2.2.1",
    "react-virtualized": "^9.12.0",
    "redux": "^4.0.5",
    "redux-actions": "^2.6.5",
    "redux-immutable": "^4.0.0",
    "redux-localstorage": "^1.0.0-rc5",
    "redux-localstorage-debounce": "^0.1.0",
    "redux-localstorage-filter": "^0.1.1",
    "redux-saga": "^1.1.3",
    "reselect": "^4.0.0",
    "seamless-immutable": "^7.0.1",
    "styled-components": "^4.0.0",
    "subscriptions-transport-ws": "^0.9.5",
    "utility-types": "^1.0.0",
    "webpack-bundle-analyzer": "^3.3.2",
    "zen-observable": "^0.7.1"
  },
  "lint-staged": {
    "*.{ts,tsx}": [
      "prettier --single-quote --no-semi --write",
      "tslint",
      "git add"
    ],
    "gitDir": "../../"
  },
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{ts,tsx}"
    ],
    "setupFiles": [
      "<rootDir>/config/polyfills.js"
    ],
    "testPathIgnorePatterns": [
      "<rootDir>[/\\\\](build|docs|node_modules)[/\\\\]"
    ],
    "testEnvironment": "node",
    "testURL": "http://localhost",
    "transform": {
      "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
      "^.+\\.tsx?$": "<rootDir>/config/jest/typescriptTransform.js",
      "^(?!.*\\.(css|json)$)": "<rootDir>/config/jest/fileTransform.js"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx)$"
    ],
    "moduleNameMapper": {
      "^react-native$": "react-native-web"
    },
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ],
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js)$"
  },
  "gitHead": "53d233f9deb9dcc86f99e41268ff92b6367e0713"
}
